# Generated by Django 6.0.3 on 2026-03-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('year_of_study', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('church_class', models.CharField(choices=[('Vine branches', 'Vine branches'), ('Children of God', 'Children of God'), ('Holy Saints', 'Holy Saints')], max_length=50)),
            ],
        ),
    ]
