# Generated by Django 6.0.3 on 2026-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='church_class',
        ),
        migrations.AddField(
            model_name='member',
            name='class_name',
            field=models.CharField(choices=[('Vine branches', 'Vine branches'), ('Bible Scholars', 'Bible Scholars'), ('LightBearers', 'LightBearers')], default='Bible Scholars', max_length=50),
        ),
    ]
