# Generated by Django 6.0.3 on 2026-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_member_church_class_member_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
