# Generated by Django 6.0.3 on 2026-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_member_registration_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'Visitor'), (6, 'Alumni'), (7, 'Staff')], default='year of study'),
        ),
    ]
